"""Regenerate Android launcher icons and Android 12+ splash icons.

Sources:
  - assets/logo/fitness_diary_compact.png   → launcher icons (full artwork)
  - assets/logo/fitness_diary_splash.png    → android12splash icons (tight
                                              diary-only crop)

Outputs:
  - android/app/src/main/res/mipmap-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi}/ic_launcher.png
  - android/app/src/main/res/drawable-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi}/ic_launcher_foreground.png
  - android/app/src/main/res/drawable-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi}/android12splash.png
  - android/app/src/main/res/drawable-night-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi}/android12splash.png
"""

from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]
ANDROID_RES = REPO_ROOT / "android" / "app" / "src" / "main" / "res"

# Launcher source: the full wordmark logo (cover with surrounding brand
# art, transparent padding, square).
LAUNCHER_SRC = REPO_ROOT / "assets" / "logo" / "fitness_diary_compact.png"

# Splash source: tight diary-only crop already centered on a 1024x1024
# transparent canvas (generated by tool/_make_tight_crop.py).
SPLASH_SRC = REPO_ROOT / "assets" / "logo" / "fitness_diary_splash.png"

# Standard Android launcher icon sizes (px).
LAUNCHER_SIZES = {
    "mdpi": 48,
    "hdpi": 72,
    "xhdpi": 96,
    "xxhdpi": 144,
    "xxxhdpi": 192,
}

# Android 12+ splash icon — sized for the 240dp / 288dp platform render
# sizes so the artwork stays crisp.
SPLASH_SIZES = {
    "mdpi": 192,
    "hdpi": 256,
    "xhdpi": 384,
    "xxhdpi": 512,
    "xxxhdpi": 768,
}


def render_at(src: Image.Image, size: int) -> Image.Image:
    """Resize preserving aspect ratio, centred on a transparent canvas."""
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    src_resized = src.copy()
    src_resized.thumbnail((size, size), Image.LANCZOS)
    ox = (size - src_resized.width) // 2
    oy = (size - src_resized.height) // 2
    canvas.paste(src_resized, (ox, oy), src_resized)
    return canvas


def main() -> None:
    if not LAUNCHER_SRC.exists():
        raise SystemExit(f"Launcher source not found: {LAUNCHER_SRC}")
    if not SPLASH_SRC.exists():
        raise SystemExit(f"Splash source not found: {SPLASH_SRC}")

    written: list[Path] = []

    with Image.open(LAUNCHER_SRC) as raw:
        launcher_source = raw.convert("RGBA")

    for density, size in LAUNCHER_SIZES.items():
        img = render_at(launcher_source, size)

        legacy = ANDROID_RES / f"mipmap-{density}" / "ic_launcher.png"
        img.save(legacy, "PNG", optimize=True)
        written.append(legacy)

        foreground = ANDROID_RES / f"drawable-{density}" / "ic_launcher_foreground.png"
        img.save(foreground, "PNG", optimize=True)
        written.append(foreground)

    with Image.open(SPLASH_SRC) as raw:
        splash_source = raw.convert("RGBA")

    for density, size in SPLASH_SIZES.items():
        img = render_at(splash_source, size)

        light = ANDROID_RES / f"drawable-{density}" / "android12splash.png"
        img.save(light, "PNG", optimize=True)
        written.append(light)

        # Dark variant — same image is fine since the new diary artwork
        # has its own dark cover background, so it reads on either splash
        # theme.
        dark = ANDROID_RES / f"drawable-night-{density}" / "android12splash.png"
        img.save(dark, "PNG", optimize=True)
        written.append(dark)

    print(f"Wrote {len(written)} files:")
    for path in written:
        print(f"  {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()